"""Audit event type constants — SR-AUTH-018."""

from enum import StrEnum


class AuditEventType(StrEnum):
    LOGIN_SUCCESS = "LOGIN_SUCCESS"
    LOGIN_FAILURE = "LOGIN_FAILURE"
    ACCOUNT_LOCKED = "ACCOUNT_LOCKED"
    PASSWORD_RESET_REQUESTED = "PASSWORD_RESET_REQUESTED"
    PASSWORD_RESET_COMPLETED = "PASSWORD_RESET_COMPLETED"
    PASSWORD_CHANGED = "PASSWORD_CHANGED"
    SESSION_INVALIDATED = "SESSION_INVALIDATED"
    ADMIN_FORCED_LOGOUT = "ADMIN_FORCED_LOGOUT"
    REGISTRATION_ATTEMPTED = "REGISTRATION_ATTEMPTED"
    EMAIL_VERIFIED = "EMAIL_VERIFIED"
    CSRF_ATTEMPT = "CSRF_ATTEMPT"
    HIBP_CHECK_FAILED = "HIBP_CHECK_FAILED"
